[terminal.shell]
program = "pwsh"
args = ["-NoLogo"]

[general]
# working_directory = ""

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "SpawnNewInstance"}
]

[window]
decorations = "full"
